//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace FileReport.RestApi.Infrastructure.Soap
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [ServiceContractAttribute(Namespace="http://project.example.com/file-report/soap", ConfigurationName="FileReport.RestApi.Infrastructure.Soap.FileReportPort")]
    public interface FileReportPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.GetFileByUuidResponse1> GetFileByUuidAsync(FileReport.RestApi.Infrastructure.Soap.GetFileByUuidRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.ListFilesByUserResponse> ListFilesByUserAsync(FileReport.RestApi.Infrastructure.Soap.ListFilesByUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedResponse> ListAllFilesPaginatedAsync(FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameResponse> SearchFilesByNameAsync(FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://project.example.com/file-report/soap")]
    public partial class GetFileByUuidRequest
    {
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://project.example.com/file-report/soap")]
    public partial class FileReportDto
    {
        
        private string uuidField;
        
        private string fileNameField;
        
        private string contentTypeField;
        
        private long fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        private string userIdField;
        
        private bool errorField;
        
        private string errorMessageField;
        
        private string mimeTypeField;
        
        private long originalSizeField;
        
        private bool originalSizeFieldSpecified;
        
        private string urlFileField;
        
        private string sha256OriginalField;
        
        private string sha256DecryptedField;
        
        private bool decryptValidationOkField;
        
        private bool decryptValidationOkFieldSpecified;
        
        private string encryptionAlgorithmField;
        
        private System.DateTime processedAtField;
        
        private bool processedAtFieldSpecified;
        
        private string encryptedAesKeyBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long fileSize
        {
            get
            {
                return this.fileSizeField;
            }
            set
            {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileSizeSpecified
        {
            get
            {
                return this.fileSizeFieldSpecified;
            }
            set
            {
                this.fileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long originalSize
        {
            get
            {
                return this.originalSizeField;
            }
            set
            {
                this.originalSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalSizeSpecified
        {
            get
            {
                return this.originalSizeFieldSpecified;
            }
            set
            {
                this.originalSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string urlFile
        {
            get
            {
                return this.urlFileField;
            }
            set
            {
                this.urlFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string sha256Original
        {
            get
            {
                return this.sha256OriginalField;
            }
            set
            {
                this.sha256OriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string sha256Decrypted
        {
            get
            {
                return this.sha256DecryptedField;
            }
            set
            {
                this.sha256DecryptedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool decryptValidationOk
        {
            get
            {
                return this.decryptValidationOkField;
            }
            set
            {
                this.decryptValidationOkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool decryptValidationOkSpecified
        {
            get
            {
                return this.decryptValidationOkFieldSpecified;
            }
            set
            {
                this.decryptValidationOkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string encryptionAlgorithm
        {
            get
            {
                return this.encryptionAlgorithmField;
            }
            set
            {
                this.encryptionAlgorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime processedAt
        {
            get
            {
                return this.processedAtField;
            }
            set
            {
                this.processedAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool processedAtSpecified
        {
            get
            {
                return this.processedAtFieldSpecified;
            }
            set
            {
                this.processedAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string encryptedAesKeyBase64
        {
            get
            {
                return this.encryptedAesKeyBase64Field;
            }
            set
            {
                this.encryptedAesKeyBase64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://project.example.com/file-report/soap")]
    public partial class GetFileByUuidResponse
    {
        
        private FileReportDto fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FileReportDto file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileByUuidRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://project.example.com/file-report/soap", Order=0)]
        public FileReport.RestApi.Infrastructure.Soap.GetFileByUuidRequest GetFileByUuidRequest;
        
        public GetFileByUuidRequest1()
        {
        }
        
        public GetFileByUuidRequest1(FileReport.RestApi.Infrastructure.Soap.GetFileByUuidRequest GetFileByUuidRequest)
        {
            this.GetFileByUuidRequest = GetFileByUuidRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileByUuidResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://project.example.com/file-report/soap", Order=0)]
        public FileReport.RestApi.Infrastructure.Soap.GetFileByUuidResponse GetFileByUuidResponse;
        
        public GetFileByUuidResponse1()
        {
        }
        
        public GetFileByUuidResponse1(FileReport.RestApi.Infrastructure.Soap.GetFileByUuidResponse GetFileByUuidResponse)
        {
            this.GetFileByUuidResponse = GetFileByUuidResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://project.example.com/file-report/soap")]
    public partial class ListFilesByUserRequest
    {
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListFilesByUserRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://project.example.com/file-report/soap", Order=0)]
        public FileReport.RestApi.Infrastructure.Soap.ListFilesByUserRequest ListFilesByUserRequest;
        
        public ListFilesByUserRequest1()
        {
        }
        
        public ListFilesByUserRequest1(FileReport.RestApi.Infrastructure.Soap.ListFilesByUserRequest ListFilesByUserRequest)
        {
            this.ListFilesByUserRequest = ListFilesByUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListFilesByUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListFilesByUserResponse", Namespace="http://project.example.com/file-report/soap", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)]
        public FileReport.RestApi.Infrastructure.Soap.FileReportDto[] ListFilesByUserResponse1;
        
        public ListFilesByUserResponse()
        {
        }
        
        public ListFilesByUserResponse(FileReport.RestApi.Infrastructure.Soap.FileReportDto[] ListFilesByUserResponse1)
        {
            this.ListFilesByUserResponse1 = ListFilesByUserResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://project.example.com/file-report/soap")]
    public partial class ListAllFilesPaginatedRequest
    {
        
        private int pageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllFilesPaginatedRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://project.example.com/file-report/soap", Order=0)]
        public FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedRequest ListAllFilesPaginatedRequest;
        
        public ListAllFilesPaginatedRequest1()
        {
        }
        
        public ListAllFilesPaginatedRequest1(FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedRequest ListAllFilesPaginatedRequest)
        {
            this.ListAllFilesPaginatedRequest = ListAllFilesPaginatedRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllFilesPaginatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllFilesPaginatedResponse", Namespace="http://project.example.com/file-report/soap", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("results", IsNullable=false)]
        public FileReport.RestApi.Infrastructure.Soap.FileReportDto[] ListAllFilesPaginatedResponse1;
        
        public ListAllFilesPaginatedResponse()
        {
        }
        
        public ListAllFilesPaginatedResponse(FileReport.RestApi.Infrastructure.Soap.FileReportDto[] ListAllFilesPaginatedResponse1)
        {
            this.ListAllFilesPaginatedResponse1 = ListAllFilesPaginatedResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://project.example.com/file-report/soap")]
    public partial class SearchFilesByNameRequest
    {
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchFilesByNameRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://project.example.com/file-report/soap", Order=0)]
        public FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameRequest SearchFilesByNameRequest;
        
        public SearchFilesByNameRequest1()
        {
        }
        
        public SearchFilesByNameRequest1(FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameRequest SearchFilesByNameRequest)
        {
            this.SearchFilesByNameRequest = SearchFilesByNameRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchFilesByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchFilesByNameResponse", Namespace="http://project.example.com/file-report/soap", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("results", IsNullable=false)]
        public FileReport.RestApi.Infrastructure.Soap.FileReportDto[] SearchFilesByNameResponse1;
        
        public SearchFilesByNameResponse()
        {
        }
        
        public SearchFilesByNameResponse(FileReport.RestApi.Infrastructure.Soap.FileReportDto[] SearchFilesByNameResponse1)
        {
            this.SearchFilesByNameResponse1 = SearchFilesByNameResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface FileReportPortChannel : FileReport.RestApi.Infrastructure.Soap.FileReportPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class FileReportPortClient : System.ServiceModel.ClientBase<FileReport.RestApi.Infrastructure.Soap.FileReportPort>, FileReport.RestApi.Infrastructure.Soap.FileReportPort
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FileReportPortClient() : 
                base(FileReportPortClient.GetDefaultBinding(), FileReportPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FileReportPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileReportPortClient(EndpointConfiguration endpointConfiguration) : 
                base(FileReportPortClient.GetBindingForEndpoint(endpointConfiguration), FileReportPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileReportPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FileReportPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileReportPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FileReportPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileReportPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.GetFileByUuidResponse1> FileReport.RestApi.Infrastructure.Soap.FileReportPort.GetFileByUuidAsync(FileReport.RestApi.Infrastructure.Soap.GetFileByUuidRequest1 request)
        {
            return base.Channel.GetFileByUuidAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.GetFileByUuidResponse1> GetFileByUuidAsync(FileReport.RestApi.Infrastructure.Soap.GetFileByUuidRequest GetFileByUuidRequest)
        {
            FileReport.RestApi.Infrastructure.Soap.GetFileByUuidRequest1 inValue = new FileReport.RestApi.Infrastructure.Soap.GetFileByUuidRequest1();
            inValue.GetFileByUuidRequest = GetFileByUuidRequest;
            return ((FileReport.RestApi.Infrastructure.Soap.FileReportPort)(this)).GetFileByUuidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.ListFilesByUserResponse> FileReport.RestApi.Infrastructure.Soap.FileReportPort.ListFilesByUserAsync(FileReport.RestApi.Infrastructure.Soap.ListFilesByUserRequest1 request)
        {
            return base.Channel.ListFilesByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.ListFilesByUserResponse> ListFilesByUserAsync(FileReport.RestApi.Infrastructure.Soap.ListFilesByUserRequest ListFilesByUserRequest)
        {
            FileReport.RestApi.Infrastructure.Soap.ListFilesByUserRequest1 inValue = new FileReport.RestApi.Infrastructure.Soap.ListFilesByUserRequest1();
            inValue.ListFilesByUserRequest = ListFilesByUserRequest;
            return ((FileReport.RestApi.Infrastructure.Soap.FileReportPort)(this)).ListFilesByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedResponse> FileReport.RestApi.Infrastructure.Soap.FileReportPort.ListAllFilesPaginatedAsync(FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedRequest1 request)
        {
            return base.Channel.ListAllFilesPaginatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedResponse> ListAllFilesPaginatedAsync(FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedRequest ListAllFilesPaginatedRequest)
        {
            FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedRequest1 inValue = new FileReport.RestApi.Infrastructure.Soap.ListAllFilesPaginatedRequest1();
            inValue.ListAllFilesPaginatedRequest = ListAllFilesPaginatedRequest;
            return ((FileReport.RestApi.Infrastructure.Soap.FileReportPort)(this)).ListAllFilesPaginatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameResponse> FileReport.RestApi.Infrastructure.Soap.FileReportPort.SearchFilesByNameAsync(FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameRequest1 request)
        {
            return base.Channel.SearchFilesByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameResponse> SearchFilesByNameAsync(FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameRequest SearchFilesByNameRequest)
        {
            FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameRequest1 inValue = new FileReport.RestApi.Infrastructure.Soap.SearchFilesByNameRequest1();
            inValue.SearchFilesByNameRequest = SearchFilesByNameRequest;
            return ((FileReport.RestApi.Infrastructure.Soap.FileReportPort)(this)).SearchFilesByNameAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FileReportPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FileReportPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8085/ws");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FileReportPortClient.GetBindingForEndpoint(EndpointConfiguration.FileReportPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FileReportPortClient.GetEndpointAddress(EndpointConfiguration.FileReportPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            FileReportPortSoap11,
        }
    }
}
